eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

spring:
  application:
    name: router
zuul:
  sensitive-headers:
  - Cookie, Authorization    
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
