spring:
  application:
    name: 'router'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  sensitive-headers:
  - Cookie, Authorization
  routes:
    spring-security-oauth-resource:
      path: /spring-security-oauth-resource/**
      url: http://localhost:8089/spring-security-oauth-resource
    oauth:
      path: /oauth/**
      url: http://localhost:8088/
      
management:
  endpoints:
    web:
      exposure:
        include:
        - "routes"
