spring:
  application:
    name: auth
  datasource:
    password: 123456
    url: jdbc:mariadb://localhost:3306/auth
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
