spring:
  application:
    name: 'resources'
  datasource:
    password: 123456
    username: root
    url: 'jdbc:mariadb://localhost:3306/resources'
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
security:
  oauth2:
    resource:
      user-info-uri: 'http://localhost:8080/auth/users/user'
api:
  moeda: 'https://economia.awesomeapi.com.br'
  base: BRL
